# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pitcher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pitcher
  pod 'Alamofire', '~> 4.7'
  pod 'RealmSwift'
  pod 'SwiftyJSON', '~> 4.0'


  target 'PitcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PitcherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
